\c ${DB_DATABASE};

CREATE TABLE emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR NOT NULL
);

CREATE TABLE phone_numbers (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR NOT NULL
);

CREATE USER ${DB_REPL_USER} WITH REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';
